version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    volumes:
      - /mnt/sonarqube:/opt/sonarqube/data  # EBS volume mounted to SonarQube data directory
    depends_on:
      - db
    networks:
      - sonarnet

  db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - sonarnet

volumes:
  sonarqube-db-data:
    driver: local

networks:
  sonarnet:
    driver: bridge
