name: SecureOpsFlow Workflow

on:
  push:
    branches:
      - main

jobs:
  code-quality-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=SecureOpsFlow_SonarQube_Analysis
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube Quality Gate
        id: quality-gate
        run: |
          status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=SecureOpsFlow_SonarQube_Analysis" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $status"
          if [[ "$status" != "OK" ]]; then
            echo "QA_STATUS=FAILED" >> $GITHUB_ENV
          else
            echo "QA_STATUS=SUCCESS" >> $GITHUB_ENV
          fi

      - name: Send Failed Email Notification
        if: ${{ env.QA_STATUS == 'FAILED' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Quality Gate Failed"
          body: "The SonarQube Quality Gate has failed. Please review the analysis results for more details."
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com

      - name: Send Passed Email Notification
        if: ${{ env.QA_STATUS == 'SUCCESS' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Quality Gate Passed"
          body: "The SonarQube Quality Gate has passed successfully. Good job!"
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com

  build-and-scan:
    name: Build and Scan Docker Image
    needs: code-quality-sonarqube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t secureopsflow:latest .

      - name: Image Scan for Vulnerabilities
        id: image_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'secureopsflow:latest'
          exit-code: 0
          ignore-unfixed: true

      - name: Dockerfile Trivy Check
        id: scan_eval
        run: |
          trivy image --severity HIGH,CRITICAL secureopsflow:latest >> SecureOpsFlow_dockerfile_vulnerability_report.txt

      - name: Send Vulnerability Report Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SecureOpsFlow Dockerfile Vulnerability Report"
          body: "Find the attached vulnerability report for SecureOpsFlow."
          attachments: SecureOpsFlow_dockerfile_vulnerability_report.txt
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com

  deploy-to-ec2:
    name: Deploy to EC2
    needs: build-and-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Application to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Stop and remove the existing container if running
          docker rm -f secureopsflow || true
          # Pull the latest image from ECR
          docker pull ${{ secrets.ECR_REGISTRY }}/secureopsflow:latest
          # Run the container
          docker run -d --name secureopsflow -p 80:80 ${{ secrets.ECR_REGISTRY }}/secureopsflow:latest
          EOF

      - name: Send Deployment Confirmation Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Deployment Successful: SecureOpsFlow"
          body: "The deployment of SecureOpsFlow to the EC2 instance was successful."
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com
