name: SecureOpsFlow Workflow

on:
  push:
    branches:
      - main

jobs:
  code-quality-sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=SecureOpsFlow_SonarQube_Analysis
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Check SonarQube Quality Gate
        id: quality-gate
        run: |
          status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=SecureOpsFlow_SonarQube_Analysis" | jq -r '.projectStatus.status')
          echo "Quality Gate Status: $status"
          if [[ "$status" != "OK" ]]; then
            echo "QA_STATUS=FAILED" >> $GITHUB_ENV
          else
            echo "QA_STATUS=SUCCESS" >> $GITHUB_ENV
          fi

      - name: Send Failed Email Notification
        if: ${{ env.QA_STATUS == 'FAILED' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Quality Gate Failed"
          body: "The SonarQube Quality Gate has failed. Please review the analysis results for more details."
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com

      - name: Send Passed Email Notification
        if: ${{ env.QA_STATUS == 'SUCCESS' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Quality Gate Passed"
          body: "The SonarQube Quality Gate has passed successfully. Good job!"
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com
        
  build-and-scan:
    name: Build and Scan Docker Image
    needs: code-quality-sonarqube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t SecureOpsFlow:latest .

      - name: Image Scan for Vulnerabilities
        id: image_scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'SecureOpsFlow:latest'
          exit-code: 0   # Allow the scan to proceed without exiting immediately
          ignore-unfixed: true

      - name: Evaluate Scan Results
        id: scan_eval
        run: |
          HIGH_COUNT=$(trivy image --no-progress --severity HIGH,CRITICAL --exit-code 0 SecureOpsFlow:latest | grep -c 'HIGH\|CRITICAL' || true)
          echo "HIGH_VULNS=${HIGH_COUNT}" >> $GITHUB_ENV
          
          echo "Total HIGH/CRITICAL Vulnerabilities Found: $HIGH_COUNT"
          
          if [ "$HIGH_COUNT" -gt 70 ]; then
            echo "STATUS=fail" >> $GITHUB_ENV
            echo "MESSAGE=Bad Work - Image scan has more than 70 vulnerabilities!" >> $GITHUB_ENV
            exit 1
          else
            echo "STATUS=pass" >> $GITHUB_ENV
            echo "MESSAGE=Good Job - Image scan passed successfully!" >> $GITHUB_ENV
          fi
