name: SecureOpsFlow Workflow

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.projectKey=SecureOpsFlow_SonarQube_Analysis
            -Dsonar.sources=.
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: SonarQube Quality Gate Check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        continue-on-error: true

      - name: Set Global Quality Gate Status
        id: set-quality-gate-status
        run: |
          status="${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}" 
          echo "Quality Gate Status: $status"
          if [[ "$status" == "FAILED" ]]; then
            echo "QA_STATUS=FAILED" >> $GITHUB_ENV
          else
            echo "QA_STATUS=SUCCESS" >> $GITHUB_ENV
          fi
          echo "Quality Gate Status: $status"

      - name: Send Failed Email Notification
        if: ${{ env.QA_STATUS == 'FAILED' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: tushargayakwad29@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "SonarQube Quality Gate Failed"
          body: "The SonarQube Quality Gate has failed. Please review the analysis results for more details."
          to: tushargayakwad2910@gmail.com
          from: tushargayakwad29@gmail.com
